import tkinter as tk
window = tk.Tk()
window.geometry("400x500+200+200")
print(window.geometry())
window.resizable(True,True)
window.minsize(200,200)
window.maxsize(800,800)
window.title("Ajay")
window.configure(bg='lightblue', cursor='hand2')
# window.state('zoomed')
# window.state('iconic')
# window.state('fullscreen')
window.attributes("-alpha",0.5)
window.attributes("-topmost",True)
# window.attributes("-fullscreen",True)
window.attributes('-toolwindow', True)
window.mainloop()
